In [28]:
import pandas as pd

In [29]:
df=pd.read_csv('5. 서울시 구별 산업별 사업체수 및 종사자수(2017-2022).csv')

In [30]:
df

,자치구,연도,건설업_사업체수,공공행정 국방 및 사회보장 행정_사업체수,광업_사업체수,교육 서비스업_사업체수,금융 및 보험업_사업체수,농업 임업 및 어업_사업체수,도매 및 소매업_사업체수,보건업 및 사회복지 서비스업_사업체수,...,수도 하수 및 폐기물 처리 원료 재생업_종사자수,숙박 및 음식점업_종사자수,예술 스포츠 및 여가관련 서비스업_종사자수,운수 및 창고업_종사자수,전기 가스 증기 및 공기조절 공급업_종사자수,전문 과학 및 기술 서비스업_종사자수,정보통신업_종사자수,제조업_종사자수,합계_종사자수,협회 및 단체 수리 및 기타 개인서비스업_종사자수
0,강남구,2017,2071.0,57.0,3,3850.0,1951.0,1,17274.0,3057.0,...,856.0,56982.0,8557.0,11093.0,1052,103202.0,58867.0,14910.0,679047.0,23193.0
1,강남구,2018,1931.0,56.0,6,3838.0,1940.0,4,16697.0,3048.0,...,823.0,58366.0,9179.0,11236.0,1222,107675.0,58879.0,14296.0,694136.0,23109.0
2,강남구,2019,1809.0,58.0,3,3903.0,1958.0,5,16401.0,3042.0,...,827.0,59357.0,9120.0,11337.0,1169,110363.0,59034.0,16875.0,698840.0,22144.0
3,강남구,2020,3399.0,59.0,6,5285.0,3589.0,39,28430.0,3467.0,...,933.0,53628.0,10059.0,12650.0,1078,138557.0,85746.0,19449.0,838446.0,24708.0
4,강남구,2021,3222.0,58.0,6,5459.0,4031.0,27,26299.0,3522.0,...,1033.0,50607.0,11059.0,12036.0,1260,133910.0,97319.0,19410.0,801419.0,21981.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,중랑구,2018,912.0,47.0,1,936.0,162.0,-,5296.0,999.0,...,228.0,11212.0,2484.0,13092.0,109,1643.0,1027.0,15250.0,103016.0,5153.0
152,중랑구,2019,965.0,47.0,-,915.0,158.0,-,5181.0,1031.0,...,206.0,11311.0,2543.0,12496.0,118,1726.0,894.0,14695.0,103345.0,5018.0
153,중랑구,2020,4409.0,47.0,1,1078.0,223.0,-,8958.0,1100.0,...,227.0,9830.0,2269.0,10648.0,180,2375.0,1712.0,14720.0,111086.0,4921.0
154,중랑구,2021,4644.0,47.0,2,1151.0,206.0,-,9064.0,1111.0,...,233.0,9997.0,2273.0,10899.0,112,2649.0,1723.0,14055.0,113144.0,4937.0
155,중랑구,2022,4763.0,46.0,2,1203.0,206.0,-,9204.0,1137.0,...,235.0,10439.0,2232.0,11235.0,108,2760.0,1849.0,14456.0,114733.0,4916.0

In [31]:
# '자치구별(2)' 행 제거
df = df[df['자치구'] != '자치구별(2)']

In [32]:

def fill_future_years(group):
    # 2021, 2022 데이터만 선택
    recent_years = group[group['연도'].isin([2021, 2022])]

    # 숫자형 열의 평균 계산 (NaN 값은 그대로 유지)
    avg_row = recent_years.mean(numeric_only=True).round()

    # 자치구 이름 유지
    avg_row['자치구'] = group['자치구'].iloc[0]

    # 2023과 2024 행 생성
    future_years = [2023, 2024]
    rows = []
    for year in future_years:
        new_row = avg_row.copy()
        new_row['연도'] = year
        rows.append(new_row)

    # 기존 데이터와 새 데이터 결합
    return pd.concat([group, pd.DataFrame(rows)], ignore_index=True)

# 그룹별로 미래 연도 데이터 채우기
df_filled = df.groupby('자치구').apply(fill_future_years).reset_index(drop=True)

In [33]:
df_filled

,자치구,연도,건설업_사업체수,공공행정 국방 및 사회보장 행정_사업체수,광업_사업체수,교육 서비스업_사업체수,금융 및 보험업_사업체수,농업 임업 및 어업_사업체수,도매 및 소매업_사업체수,보건업 및 사회복지 서비스업_사업체수,...,수도 하수 및 폐기물 처리 원료 재생업_종사자수,숙박 및 음식점업_종사자수,예술 스포츠 및 여가관련 서비스업_종사자수,운수 및 창고업_종사자수,전기 가스 증기 및 공기조절 공급업_종사자수,전문 과학 및 기술 서비스업_종사자수,정보통신업_종사자수,제조업_종사자수,합계_종사자수,협회 및 단체 수리 및 기타 개인서비스업_종사자수
0,강남구,2017,2071.0,57.0,3,3850.0,1951.0,1,17274.0,3057.0,...,856.0,56982.0,8557.0,11093.0,1052,103202.0,58867.0,14910.0,679047.0,23193.0
1,강남구,2018,1931.0,56.0,6,3838.0,1940.0,4,16697.0,3048.0,...,823.0,58366.0,9179.0,11236.0,1222,107675.0,58879.0,14296.0,694136.0,23109.0
2,강남구,2019,1809.0,58.0,3,3903.0,1958.0,5,16401.0,3042.0,...,827.0,59357.0,9120.0,11337.0,1169,110363.0,59034.0,16875.0,698840.0,22144.0
3,강남구,2020,3399.0,59.0,6,5285.0,3589.0,39,28430.0,3467.0,...,933.0,53628.0,10059.0,12650.0,1078,138557.0,85746.0,19449.0,838446.0,24708.0
4,강남구,2021,3222.0,58.0,6,5459.0,4031.0,27,26299.0,3522.0,...,1033.0,50607.0,11059.0,12036.0,1260,133910.0,97319.0,19410.0,801419.0,21981.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,중랑구,2020,4409.0,47.0,1,1078.0,223.0,-,8958.0,1100.0,...,227.0,9830.0,2269.0,10648.0,180,2375.0,1712.0,14720.0,111086.0,4921.0
196,중랑구,2021,4644.0,47.0,2,1151.0,206.0,-,9064.0,1111.0,...,233.0,9997.0,2273.0,10899.0,112,2649.0,1723.0,14055.0,113144.0,4937.0
197,중랑구,2022,4763.0,46.0,2,1203.0,206.0,-,9204.0,1137.0,...,235.0,10439.0,2232.0,11235.0,108,2760.0,1849.0,14456.0,114733.0,4916.0
198,중랑구,2023,4704.0,46.0,NaN,1177.0,206.0,NaN,9134.0,1124.0,...,234.0,10218.0,2252.0,11067.0,NaN,2704.0,1786.0,14256.0,113938.0,4926.0
199,중랑구,2024,4704.0,46.0,NaN,1177.0,206.0,NaN,9134.0,1124.0,...,234.0,10218.0,2252.0,11067.0,NaN,2704.0,1786.0,14256.0,113938.0,4926.0

In [34]:
print(df_filled)

     자치구    연도  건설업_사업체수  공공행정 국방 및 사회보장 행정_사업체수 광업_사업체수  교육 서비스업_사업체수  \
0    강남구  2017    2071.0                    57.0       3        3850.0
1    강남구  2018    1931.0                    56.0       6        3838.0
2    강남구  2019    1809.0                    58.0       3        3903.0
3    강남구  2020    3399.0                    59.0       6        5285.0
4    강남구  2021    3222.0                    58.0       6        5459.0
..   ...   ...       ...                     ...     ...           ...
195  중랑구  2020    4409.0                    47.0       1        1078.0
196  중랑구  2021    4644.0                    47.0       2        1151.0
197  중랑구  2022    4763.0                    46.0       2        1203.0
198  중랑구  2023    4704.0                    46.0     NaN        1177.0
199  중랑구  2024    4704.0                    46.0     NaN        1177.0

     금융 및 보험업_사업체수 농업 임업 및 어업_사업체수  도매 및 소매업_사업체수  보건업 및 사회복지 서비스업_사업체수  ...  \
0           1951.0               1        17274.0                3057.0  ...
1           1940.0               4        16697.0                3048.0  ...
2           1958.0               5        16401.0                3042.0  ...
3           3589.0              39        28430.0                3467.0  ...
4           4031.0              27        26299.0                3522.0  ...
..             ...             ...            ...                   ...  ...
195          223.0               -         8958.0                1100.0  ...
196          206.0               -         9064.0                1111.0  ...
197          206.0               -         9204.0                1137.0  ...
198          206.0             NaN         9134.0                1124.0  ...
199          206.0             NaN         9134.0                1124.0  ...

     수도 하수 및 폐기물 처리 원료 재생업_종사자수  숙박 및 음식점업_종사자수 예술 스포츠 및 여가관련 서비스업_종사자수  \
0                         856.0         56982.0                  8557.0
1                         823.0         58366.0                  9179.0
2                         827.0         59357.0                  9120.0
3                         933.0         53628.0                 10059.0
4                        1033.0         50607.0                 11059.0
..                          ...             ...                     ...
195                       227.0          9830.0                  2269.0
196                       233.0          9997.0                  2273.0
197                       235.0         10439.0                  2232.0
198                       234.0         10218.0                  2252.0
199                       234.0         10218.0                  2252.0

     운수 및 창고업_종사자수  전기 가스 증기 및 공기조절 공급업_종사자수  전문 과학 및 기술 서비스업_종사자수  \
0          11093.0                      1052              103202.0
1          11236.0                      1222              107675.0
2          11337.0                      1169              110363.0
3          12650.0                      1078              138557.0
4          12036.0                      1260              133910.0
..             ...                       ...                   ...
195        10648.0                       180                2375.0
196        10899.0                       112                2649.0
197        11235.0                       108                2760.0
198        11067.0                       NaN                2704.0
199        11067.0                       NaN                2704.0

     정보통신업_종사자수 제조업_종사자수   합계_종사자수  협회 및 단체 수리 및 기타 개인서비스업_종사자수
0       58867.0  14910.0  679047.0                      23193.0
1       58879.0  14296.0  694136.0                      23109.0
2       59034.0  16875.0  698840.0                      22144.0
3       85746.0  19449.0  838446.0                      24708.0
4       97319.0  19410.0  801419.0                      21981.0
..          ...      ...       ...                          ...
195      1712.0  14720.0  111086.0                       4921.0
196      1723.0  14055.0  113144.0                       4937.0
197      1849.0  14456.0  114733.0                       4916.0
198      1786.0  14256.0  113938.0                       4926.0
199      1786.0  14256.0  113938.0                       4926.0

[200 rows x 44 columns]

In [35]:
df_filled.to_csv('사업체 수정.csv',index=False)

In [ ]:
#2023,2024 데이터는 없어서 2021,2022 데이터를 평균낸 값을 2023과 2024를 추가해서 대입했음.